# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/mainapp/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pluginGroup = QtWidgets.QGroupBox(self.centralWidget)
        self.pluginGroup.setObjectName("pluginGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pluginGroup)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pluginLayout = QtWidgets.QVBoxLayout()
        self.pluginLayout.setSpacing(6)
        self.pluginLayout.setObjectName("pluginLayout")
        self.gridLayout_4.addLayout(self.pluginLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.pluginGroup, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graphicsView = QEnhancedGraphicsView(self.groupBox)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_6.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewOriginalCheck = QtWidgets.QCheckBox(self.groupBox)
        self.viewOriginalCheck.setObjectName("viewOriginalCheck")
        self.horizontalLayout.addWidget(self.viewOriginalCheck)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 25))
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Plugins = QtWidgets.QMenu(self.menuBar)
        self.menu_Plugins.setObjectName("menu_Plugins")
        self.menu_Options = QtWidgets.QMenu(self.menuBar)
        self.menu_Options.setObjectName("menu_Options")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionLanguage = QtWidgets.QAction(MainWindow)
        self.actionLanguage.setObjectName("actionLanguage")
        self.actionTheme = QtWidgets.QAction(MainWindow)
        self.actionTheme.setObjectName("actionTheme")
        self.action_Camera = QtWidgets.QAction(MainWindow)
        self.action_Camera.setObjectName("action_Camera")
        self.menu_File.addAction(self.actionOpenImage)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSaveImage)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_Options.addAction(self.actionLanguage)
        self.menu_Options.addAction(self.actionTheme)
        self.menu_Help.addAction(self.actionAboutQt)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menu_Plugins.menuAction())
        self.menuBar.addAction(self.menu_Options.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Machina -- Machine Vision"))
        self.pluginGroup.setTitle(_translate("MainWindow", "Plugin UI"))
        self.groupBox.setTitle(_translate("MainWindow", "View"))
        self.viewOriginalCheck.setText(_translate("MainWindow", "View Original Image"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Plugins.setTitle(_translate("MainWindow", "&Plugins"))
        self.menu_Options.setTitle(_translate("MainWindow", "O&ptions"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionOpenImage.setText(_translate("MainWindow", "&Open Image"))
        self.actionOpenImage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveImage.setText(_translate("MainWindow", "&Save Image"))
        self.actionSaveImage.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionAboutQt.setText(_translate("MainWindow", "&About Qt"))
        self.actionLanguage.setText(_translate("MainWindow", "Language"))
        self.actionTheme.setText(_translate("MainWindow", "Theme"))
        self.action_Camera.setText(_translate("MainWindow", "&Camera"))

from .qenhancedgraphicsview import QEnhancedGraphicsView
